@MongoDBConnection_HostAddress = http://localhost:5217


###  
//// students 

@id=699730a39d3f2c958a1bf7b5

GET {{MongoDBConnection_HostAddress}}/students

###

GET {{MongoDBConnection_HostAddress}}/students/{{id}}

###

POST {{MongoDBConnection_HostAddress}}/students
Content-Type: application/json

{
  "name":"rita",
  "email":"RITA@gmail.com",
  "address":"Patan"
}

###

DELETE {{MongoDBConnection_HostAddress}}/students/{{id}}

###

PUT {{MongoDBConnection_HostAddress}}/students/{{id}}
Content-Type: application/json

{
  "name":"Shyam"
}

###

////// courses

@courseId = 699821bc1d61a72162966c71

GET {{MongoDBConnection_HostAddress}}/courses

###

GET {{MongoDBConnection_HostAddress}}/courses/{{courseId}}

###

PUT {{MongoDBConnection_HostAddress}}/courses/{{courseId}}
Content-Type: application/json

{
  "title":"C Programming"
}

###

POST {{MongoDBConnection_HostAddress}}/courses
Content-Type: application/json

{
  "title":"Test",
  "description":"To learn other programming languages you should learn C programming first.",
  "creditHours": 25
}

###

DELETE {{MongoDBConnection_HostAddress}}/courses/{{courseId}}

###


////// enrollments

@enrollmentId = 69985ed61121e7ca5ade24ac

GET {{MongoDBConnection_HostAddress}}/enrollments

###

GET {{MongoDBConnection_HostAddress}}/enrollments/{{enrollmentId}}


###

POST {{MongoDBConnection_HostAddress}}/enrollments
Content-Type: application/json

{
  "student":"699730a39d3f2c958a1bf7b5",
  "course":"699821bc1d61a72162966c71"
}

###

DELETE {{MongoDBConnection_HostAddress}}/enrollments/{{enrollmentId}}

###
